[project]
name = "chumpstreet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.3",
    "fredapi>=0.5.2",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "yfinance>=0.2.65",
]
